// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: protos/moviesapp.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MoviesappClient is the client API for Moviesapp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoviesappClient interface {
	GetMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Moviesapp_GetMoviesClient, error)
	GetMovie(ctx context.Context, in *Id, opts ...grpc.CallOption) (*MovieInfo, error)
	CreateMovie(ctx context.Context, in *MovieInfo, opts ...grpc.CallOption) (*Id, error)
	UpdateMovie(ctx context.Context, in *MovieInfo, opts ...grpc.CallOption) (*Status, error)
	DeleteMovie(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Status, error)
}

type moviesappClient struct {
	cc grpc.ClientConnInterface
}

func NewMoviesappClient(cc grpc.ClientConnInterface) MoviesappClient {
	return &moviesappClient{cc}
}

func (c *moviesappClient) GetMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Moviesapp_GetMoviesClient, error) {
	stream, err := c.cc.NewStream(ctx, &Moviesapp_ServiceDesc.Streams[0], "/moviesapp.Moviesapp/GetMovies", opts...)
	if err != nil {
		return nil, err
	}
	x := &moviesappGetMoviesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Moviesapp_GetMoviesClient interface {
	Recv() (*MovieInfo, error)
	grpc.ClientStream
}

type moviesappGetMoviesClient struct {
	grpc.ClientStream
}

func (x *moviesappGetMoviesClient) Recv() (*MovieInfo, error) {
	m := new(MovieInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *moviesappClient) GetMovie(ctx context.Context, in *Id, opts ...grpc.CallOption) (*MovieInfo, error) {
	out := new(MovieInfo)
	err := c.cc.Invoke(ctx, "/moviesapp.Moviesapp/GetMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesappClient) CreateMovie(ctx context.Context, in *MovieInfo, opts ...grpc.CallOption) (*Id, error) {
	out := new(Id)
	err := c.cc.Invoke(ctx, "/moviesapp.Moviesapp/CreateMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesappClient) UpdateMovie(ctx context.Context, in *MovieInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/moviesapp.Moviesapp/UpdateMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesappClient) DeleteMovie(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/moviesapp.Moviesapp/DeleteMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoviesappServer is the server API for Moviesapp service.
// All implementations must embed UnimplementedMoviesappServer
// for forward compatibility
type MoviesappServer interface {
	GetMovies(*Empty, Moviesapp_GetMoviesServer) error
	GetMovie(context.Context, *Id) (*MovieInfo, error)
	CreateMovie(context.Context, *MovieInfo) (*Id, error)
	UpdateMovie(context.Context, *MovieInfo) (*Status, error)
	DeleteMovie(context.Context, *Id) (*Status, error)
	mustEmbedUnimplementedMoviesappServer()
}

// UnimplementedMoviesappServer must be embedded to have forward compatible implementations.
type UnimplementedMoviesappServer struct {
}

func (UnimplementedMoviesappServer) GetMovies(*Empty, Moviesapp_GetMoviesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMovies not implemented")
}
func (UnimplementedMoviesappServer) GetMovie(context.Context, *Id) (*MovieInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovie not implemented")
}
func (UnimplementedMoviesappServer) CreateMovie(context.Context, *MovieInfo) (*Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMovie not implemented")
}
func (UnimplementedMoviesappServer) UpdateMovie(context.Context, *MovieInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMovie not implemented")
}
func (UnimplementedMoviesappServer) DeleteMovie(context.Context, *Id) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMovie not implemented")
}
func (UnimplementedMoviesappServer) mustEmbedUnimplementedMoviesappServer() {}

// UnsafeMoviesappServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoviesappServer will
// result in compilation errors.
type UnsafeMoviesappServer interface {
	mustEmbedUnimplementedMoviesappServer()
}

func RegisterMoviesappServer(s grpc.ServiceRegistrar, srv MoviesappServer) {
	s.RegisterService(&Moviesapp_ServiceDesc, srv)
}

func _Moviesapp_GetMovies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MoviesappServer).GetMovies(m, &moviesappGetMoviesServer{stream})
}

type Moviesapp_GetMoviesServer interface {
	Send(*MovieInfo) error
	grpc.ServerStream
}

type moviesappGetMoviesServer struct {
	grpc.ServerStream
}

func (x *moviesappGetMoviesServer) Send(m *MovieInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _Moviesapp_GetMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesappServer).GetMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moviesapp.Moviesapp/GetMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesappServer).GetMovie(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Moviesapp_CreateMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesappServer).CreateMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moviesapp.Moviesapp/CreateMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesappServer).CreateMovie(ctx, req.(*MovieInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Moviesapp_UpdateMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesappServer).UpdateMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moviesapp.Moviesapp/UpdateMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesappServer).UpdateMovie(ctx, req.(*MovieInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Moviesapp_DeleteMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesappServer).DeleteMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moviesapp.Moviesapp/DeleteMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesappServer).DeleteMovie(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

// Moviesapp_ServiceDesc is the grpc.ServiceDesc for Moviesapp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Moviesapp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moviesapp.Moviesapp",
	HandlerType: (*MoviesappServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovie",
			Handler:    _Moviesapp_GetMovie_Handler,
		},
		{
			MethodName: "CreateMovie",
			Handler:    _Moviesapp_CreateMovie_Handler,
		},
		{
			MethodName: "UpdateMovie",
			Handler:    _Moviesapp_UpdateMovie_Handler,
		},
		{
			MethodName: "DeleteMovie",
			Handler:    _Moviesapp_DeleteMovie_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMovies",
			Handler:       _Moviesapp_GetMovies_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/moviesapp.proto",
}
